/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package langam;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author n.oulis
 */
public class Langam extends javax.swing.JFrame
{

  /**
   * Creates new form main
   */
  private final JFileChooser filech;
  public Langam()
  {
    initComponents();
    this.setIconImage(new ImageIcon("assets\\translate.png").getImage());
    this.setTitle("Translation");
    filech = new JFileChooser();
    filech.setFileSelectionMode(JFileChooser.FILES_ONLY);
    filech.setFileFilter(new FileNameExtensionFilter("TEXT FILES","txt"));

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        start_bt = new javax.swing.JButton();
        save_bt = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 40));

        jLabel1.setText("Μεταφρασμένο");

        start_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/langam/assets/play-round-button.png"))); // NOI18N
        start_bt.setText("Start");
        start_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btActionPerformed(evt);
            }
        });

        save_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/langam/assets/floppy-disk.png"))); // NOI18N
        save_bt.setText("Save");
        save_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btActionPerformed(evt);
            }
        });

        jScrollPane7.setEnabled(false);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea4KeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(jTextArea4);

        jScrollPane7.setViewportView(jScrollPane8);

        jTextField1.setText("C:\\GANDALF\\PROJECTS\\TRASH_PROJECTS\\Langam\\Files\\area.txt");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/langam/assets/archeology.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Open....");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(start_bt)
                                .addGap(28, 28, 28)
                                .addComponent(save_bt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_bt)
                    .addComponent(jButton4)
                    .addComponent(save_bt))
                .addGap(39, 39, 39))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jlabel1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void start_btActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_start_btActionPerformed
  {//GEN-HEADEREND:event_start_btActionPerformed
    // TODO add your handling code here:
    start_bt.setEnabled(false);
    System.out.println("Start button pressed");
    
    try{
      FileReader file = new FileReader(jTextField1.getText());
      BufferedReader br = new BufferedReader(file);
      String line;

      
          jTextArea4.read(br, null);
          //jTextArea4.append("\n");
      
      br.close();
      file.close();
    }
    catch(FileNotFoundException e){
      JOptionPane.showMessageDialog(this,e.getMessage(),
    "File Error", JOptionPane.ERROR_MESSAGE);
      start_bt.setEnabled(true);
    }
    catch(IOException e){
      JOptionPane.showMessageDialog(this,e.getMessage(),
    "File Error", JOptionPane.ERROR_MESSAGE);
      start_bt.setEnabled(true);
    }
    
    
  }//GEN-LAST:event_start_btActionPerformed

  private void save_btActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_save_btActionPerformed
  {//GEN-HEADEREND:event_save_btActionPerformed
    // TODO add your handling code here:
    save_bt.setEnabled(false);
    System.out.println("Save button pressed");
    if(jTextArea4.getText()==null || jTextArea4.getText().isEmpty()){
      JOptionPane.showMessageDialog(this,"The Texts area is empty. Nothing to save!",
    "Save File", JOptionPane.WARNING_MESSAGE);
      save_bt.setEnabled(true);
    }
    else{
      try
      {
        FileWriter file = new FileWriter("Files\\output.txt");
        BufferedWriter bw = new BufferedWriter(file);
        jTextArea4.write(bw);
        bw.close();
        file.close();
      }
      catch (IOException ex)
      {
        Logger.getLogger(Langam.class.getName()).log(Level.SEVERE, null, ex);
      }
      
    }
  }//GEN-LAST:event_save_btActionPerformed

  private void jTextArea4KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea4KeyTyped
  {//GEN-HEADEREND:event_jTextArea4KeyTyped
    // TODO add your handling code here:
    start_bt.setEnabled(true);
    save_bt.setEnabled(true);
  }//GEN-LAST:event_jTextArea4KeyTyped

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
  {//GEN-HEADEREND:event_jButton3ActionPerformed
    // TODO add your handling code here:
    openFile();
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
  {//GEN-HEADEREND:event_jButton4ActionPerformed
    // TODO add your handling code here:
    jTextArea4.setText("");
    start_bt.setEnabled(true);
    save_bt.setEnabled(true);
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
  {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
    // TODO add your handling code here:
    openFile();
  }//GEN-LAST:event_jMenuItem1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(Langam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(Langam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(Langam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(Langam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new Langam().setVisible(true);
      }
    });
  }
  
  public void openFile(){
    int value = filech.showOpenDialog(this);
    
    if(value == JFileChooser.APPROVE_OPTION){
      jTextField1.setText(filech.getSelectedFile().getAbsolutePath());
    }
    else{
      JOptionPane.showMessageDialog(this,"No file chosen",
    "Open File", JOptionPane.WARNING_MESSAGE);
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton save_bt;
    private javax.swing.JButton start_bt;
    // End of variables declaration//GEN-END:variables
}
